---
:api_key: 17168c5d2df71f399c3247dfe68ee3ff
:password: a9796a72374207a7d07cb51e7dd3b6bb
:store: urbanzen.myshopify.com
:theme_id: 92809796
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
