---
:api_key: bb9fd77711e070cfe75c03f8c078d858
:password: 0cdea3f454f19633211777a5993ae656
:store: urban-zen-foundation.myshopify.com
:theme_id:
:whitelist_files:
- layout/
- assets/
- config/
- snippets/
- templates/
- locales/
